### ISSUE TITLE
Possibly Depreciated VUE Service in Use

### ISSUE THREAD

**Issue by Tbluswritescode** [mrmechko/revue#2]
When running the `npm run serve` command through the bash terminal in Sourcetree the normal start of command text appears as usual for this environment.  Following the first two lines of text 

`> revue-client@0.1.0 serve Your\path\here`
`> vue-cli-service serve`

but following these lines are two I have not seen before.  The first states that Vue CLI now supports Vue 3 by default. The second states that 

`vue-cli-plugin-vue-next is no longer needed, please remove it from the dependencies.`

While I do not know enough about Vue to be sure, I think this may be an example of a depreciated service still included in the dependencies for the project, despite no longer being needed.

**Comment by mrmechko** [comment]
This may be resolved by running `vue upgrade` in the `client/`. Will need to test the resulting system before pushing.

**Comment by mrmechko** [comment]
Make sure to rerun `npm install` after incorporating this change.
